package day42_Exceptions;

public class ThrowsKeyWord2 {
    public static void main(String[] args) {
// throws ArithmeticException won't work here because it can only get rid of checked exceptions and what we have here is a run time exception
        System.out.println("Test started");
        System.out.println(8/0);
        System.out.println("Test completed");












    }
}
